### ISSUE TITLE
Remove GET

### ISSUE THREAD

**Issue by romanojd** [OpenC2-org/openc2-org#13]
### PROBLEM

The act of "getting" is embedded into other actions, e.g., UPDATE, DETONATE. And data retrieval is always followed by an action.

---
### POTENTIAL SOLUTION

Remove GET.

**Comment by davaya** [comment]
Agree with removing GET, it is not needed.

**Comment by jmbrule** [comment]
Based on the slack channel discussions, may I suggest we remove GET from the LDD and close this action?
