### ISSUE TITLE
Remove MODIFY

### ISSUE THREAD

**Issue by romanojd** [OpenC2-org/openc2-org#14]
### PROBLEM

The CRUD semantics for OpenC2 are SET / QUERY / SET / DELETE. This makes MODIFY redundant.

---
### POTENTIAL SOLUTION

Remove MODIFY from the list of actions.

**Comment by davaya** [comment]
Agree with removing MODIFY.  A SET command will create a value if it does not exist, or modify the value if it does.

**Comment by davaya** [comment]
Agree to remove MODIFY.  SET will create a value if it does not exist, and modify the value if it already exists.

**Comment by jmbrule** [comment]
Based on the slack channel discussion, may I suggest we remove Modify from the LDD and close this action?
