### ISSUE TITLE
Use Markdown instead of DOCX

### ISSUE THREAD

**Issue by pwrdwnsys** [OpenC2-org/openc2-org#2]
The current DOCX format for the documentation means that Github can't show users the changes that are being made ("Binary file not shown.")

By changing the documents to Markdown, Github can directly show the changes which are being made, and should also be more accessible for contributions from those without Microsoft Word (or LibreOffice).

**Comment by romanojd** [comment]
Great suggestion! I currently have the details of the Language Description Document formatted in markdown, but not the front matter. I can make the translation prior to the next updates. We can use v1.0 as the initial baseline going forward.

**Comment by davaya** [comment]
Github also previews PDF nicely, so if there is content (like powerpoint slides or word diagrams) that aren't easily accommodated in markdown, saving the PDFs on Github works fine.

-----Original Message-----

**Comment by romanojd** [comment]
I added the front matter to the markdown version of the Language Description Document. You can find it here:  [docs-pub](https://github.com/OpenC2-org/docs-pub).

This markdown version is consistent with the 1.0 version of the Word Document and PDF, with the exception of Appendix, which is not complete. But everything else should be there.

This all may be moot, however, if the group decides to use Google Docs for working versions of our documents.

**Comment by romanojd** [comment]
The appendix is now complete. This issue is now closed, although, since we're now talking about using Google Docs, this may be OBE.
