### ISSUE TITLE
Sample JSON for testing

### ISSUE THREAD

**Issue by sparrell** [OpenC2-org/openc2-org#3]
### PROBLEM

There doesn't exist (to my knowledge) a set of "sample openc2 json data". This would be very useful for testing. Now each developer makes up some data on their own. For example there are some example jsons in python within https://github.com/OpenC2-org/openc2-org/blob/master/ref-implementations/OC2Tools/produce-cmd.py and some in erlang at https://github.com/sparrell/ocas/tree/master/include and probably others elsewhere.

It would be useful to go to a common place that had raw json files that each of us could use (and add to) when we needed test data. I believe it would also be helpful for validating the spec as creating these files causes you to think thru what the command should be in the use case you are thinking of.
### POTENTIAL SOLUTION

Make a directory called ExampleJson (or whatever you want to call it) in a fairly accessible place (maybe at top level of this repo, or maybe directly under ref-implementations) and populate with raw json files using some agreed upon naming convention.

**Comment by jmbrule** [comment]
I agree with your proposed solution, I will ask Jason to set it up.  I believe there are some sample json files in yuuki/examples, will have them copied and put in the new directory

-----Original Message-----

**Comment by romanojd** [comment]
I'll setup the framework so that members can upload their own examples.

**Comment by romanojd** [comment]
I added a folder for examples here: https://github.com/OpenC2-org/openc2-org/tree/master/schemas/json/examples

Is this too deep? We already had the `schemas/json` folder.

**Comment by davaya** [comment]
I will extract the JSON examples from OC2Tools/oc2test.py and put them in the examples folder Jason has created.   That file also contains several negative examples that should fail validation, which is just as important a component of a test corpus.  Unfortunately the negative examples are fuzzed from a previous version of the schema, and while they will fail to validate under the current schema, we should also have a set that is fuzzed from the current schema.  I'll create some current negative examples as time permits.

Dave

-----Original Message-----

**Comment by romanojd** [comment]
The examples can be found here: https://github.com/OpenC2-org/openc2-org/tree/master/schemas/json/examples.

As discussed in the Forum Meeting on 1/19/2017, this issue is closed.
