### ISSUE TITLE
RESPONSE and ALERT

### ISSUE THREAD

**Issue by romanojd** [OpenC2-org/openc2-org#5]
### PROBLEM

There were several comments that came out at the Face-to-Face Meeting, on 09/29, that said that it was unclear how one would use RESPONSE and ALERT. It was discussed at the bi-weekly meeting on 10/13 that the Language Description Document describes the definition and syntax of RESPONSE and ALERT, but not how they could be used.

---
### POTENTIAL SOLUTION

Current response usage patterns, presented at the bi-weekly meeting on 10/13 should be documented online and used as a reference for future implementations.

**Comment by romanojd** [comment]
I'm not sure if GitHub or Google Docs would be the best place to document response usage patterns. Maybe we could develop them in Google Docs, allowing everyone to comment on existing and propose new patterns. Then we could transition them to GitHub at the appropriate level of maturity.

**Comment by jmbrule** [comment]
Based on my interpretation of the face to face, the issue was not so much 'how to use it' as how to populate it.  The early implementers were treating it as a free flowing text field, which will impact interoperability.  

-----Original Message-----

**Comment by romanojd** [comment]
Yes, that's definitely important when looking at the different patterns. And the information that you include in the message depends on "how you're using it", i.e., the pattern.

**Comment by jtcbrule** [comment]
Use this issue tracker, until (if?) that becomes unwieldy, then transition over to a wiki page(s)?

I'm under the impression that RESPONSE is a synchronous response to an OpenC2 command and ALERT is an asyncrhonous message sent back up to (usually) the orchestrator.

The only fields that make sense universally as a response are a UUID and maybe a status code. Everything else is target/actuator/context-dependent. UUID seems to map onto a 'modifier' pretty well. But even status codes are iffy. Success for an HTTP request is 200, success for a posix function call is 0. It seems like a minimal amount of structure should be required for every command, and the rest be defined in 'data models' similar to how targets and actuators are done now.

**Comment by sparrell** [comment]
I vote we use issue tracker to (1) document that there is an issue and (2) the solution once reached (or a reference to it). I think slack should be used for all the discussion in-between (1) and (2)

**Comment by jyoverma** [comment]
I vote for discussion on slack and here until a solution is reached.

**Comment by jyoverma** [comment]
I'm looking at the current schema for RESPONSE and below are my thoughts.

Commands that need a response back should specify so using modifiers. The following modifiers could be used for this:
- Id that could carry the UUID.
- Where the response should be directed could be specified in the "destination" modifier and we could use "report-to" for that.
  "destination": {
          "enum": [
            "report-to",
            "set-to",
            "move-to",
            "save-to",
            "modify-to",
            "copy-to",
            "restore-point"
          ]
        }

The "response" can be set in the response action that comes back from the actuator and "command-ref" could carry the UUID/ID of the original command. 
"response": {
            "enum": [
              "acknowledge",
              "status",
              "query",
              "command-ref"
            ]
          }

There isn't a modifier today that the call out if a response is needed. Perhaps we can add that?

**Comment by jordan2175** [comment]
Do you want me to setup a Slack instance for OpenC2?

Bret 

Sent from my Commodore 64

PGP Fingerprint: 63B4 FC53 680A 6B7D 1447  F2C0 74F8 ACAE 7415 0050

**Comment by ldsalazar3** [comment]
A slack channel for OpenC2 already exists – openc2-community.

I can add you to it.  What’s your email address?

**Comment by jordan2175** [comment]
Just this email address.

Thanks,
Bret
PGP Fingerprint: 63B4 FC53 680A 6B7D 1447  F2C0 74F8 ACAE 7415 0050
"Without cryptography vihv vivc ce xhrnrw, however, the only thing that can not be unscrambled is an egg."

**Comment by ldsalazar3** [comment]
Use notifications@github.com?

**Comment by jordan2175** [comment]
jordan2175@gmail.com mailto:jordan2175@gmail.com

From the CC line of the email.

Thanks,
Bret
PGP Fingerprint: 63B4 FC53 680A 6B7D 1447  F2C0 74F8 ACAE 7415 0050
"Without cryptography vihv vivc ce xhrnrw, however, the only thing that can not be unscrambled is an egg."

**Comment by romanojd** [comment]
The "origin" modifier needs to be separate from "command-ref" because the same command could have been issued to multiple actuators. In the corresponding response, the "command-ref" identifies which command it is a response to and the "origin" tells where it's coming from.

BTW, would it be easier to have this discussion on Slack? Would we have it on the #issues channel or create a temporary, specific channel just for this particular issue?

**Comment by sparrell** [comment]
I vote github just be used for stating the problem, and once resolved stating the resolution. But I vote all the discussions take place on slack

**Comment by jmbrule** [comment]
Move the discussion to slack because Jyoti thinks it will give us a 'cool' factor...  

Your point on command reference is taken, given that I would 'vote' for option A  Define an origin field in the frame rather than reuse the actuator field

-----Original Message-----

**Comment by romanojd** [comment]
I created the following slack channel to discuss this issue further:

https://openc2-community.slack.com/messages/issue_response/

We'll write the final resolution here.

**Comment by romanojd** [comment]
@jtcb, Josh, are you going to continue in this discussion? Would you like an invitation to the Slack group?

**Comment by jtcbrule** [comment]
I don't have much to say on this issue, but it a slack invitation could be useful for future issues.

(What happened to people just using IRC?)

**Comment by davaya** [comment]
Discussion is now on slack.  But to synopsize here, I suggest that a new structure(s) be defined for Response and Alert rather than abusing the syntax of OpenC2 commands:

```
OpenC2Command ::= RECORD {
    action      Action,
    target      Target,
    actuator    Actuator OPTIONAL,
    modifiers   Modifiers OPTIONAL
}

OpenC2Response ::= RECORD {
    cmdref      UTF8String,      -- or UUID?
    results     UTF8String
}

OpenC2Alert ::= RECORD {
    message     UTF8String
}

OpenC2Object ::= CHOICE {
    command     OpenC2Command,
    response    OpenC2Response,
    alert       OpenC2Alert
}
```

**Comment by jmbrule** [comment]
I believe we can close this issue;

**Comment by romanojd** [comment]
RESPONSE and ALERT have been defined in more detail. We will continue to refine the response design as we develop actuator profiles.
