### ISSUE TITLE
Have a Google doc version of OpenC2

### ISSUE THREAD

**Issue by jyoverma** [OpenC2-org/openc2-org#7]
This was discussed in the previous OpenC2 STIX COA working group meeting. It was suggested that we have a google doc version of OpenC2 that's easier to contribute to. Bret offered help to set one up and maintain it.

**Comment by romanojd** [comment]
I'm working on putting it out on Google Docs. We might even, already have a Google Apps account. I'm looking into that, too. We'll keep this issue open as a reminder that we need to complete this. Thanks.

**Comment by jordan2175** [comment]
It is not that hard... Just create a Google Document and then share it with people.  The one caveat is people need to have a Google ID (aka Gmail account) to edit the document.  But that seems like a pretty low bar.

Thanks,
Bret
PGP Fingerprint: 63B4 FC53 680A 6B7D 1447  F2C0 74F8 ACAE 7415 0050
"Without cryptography vihv vivc ce xhrnrw, however, the only thing that can not be unscrambled is an egg."

**Comment by sparrell** [comment]
Done
