### ISSUE TITLE
openc2.org website has broken link

### ISSUE THREAD

**Issue by sparrell** [OpenC2-org/openc2-org#8]
### PROBLEM

Go to http://openc2.org/, 
click on the language tab, 
click on targets,
click on target details - the link can't be found

---
### POTENTIAL SOLUTION
find where it should link to and fix it

is the website content made from github? If not, should it be?

**Comment by romanojd** [comment]
Thanks for catching that. I forgot to update the links after I updated the Language Description Document on GitHub.
